### ISSUE TITLE
Some PDF not load proper

### ISSUE THREAD

**Issue by bhavin-chauhan** [JoanZapata/android-pdfview#100]
Hi, Thanks for this library.
I have setup it and try to load pdf from SDcard. I have check some of PDF file not open properly. While it was open in adobe reader and mupdf sample App.
![screenshot_2015-05-08-17-14-10](https://cloud.githubusercontent.com/assets/6767645/7535748/24f1180e-f5a6-11e4-932b-9018604a5d27.png)

I have write this code to load file.
File objPDF=new File(android.os.Environment.getExternalStorageDirectory().toString() +"/"+ "APP/File.pdf");
pdfView.fromFile(objPDF)
.defaultPage(pageNumber)
.onPageChange(this)
.load();

I have checked this problem was not occurred in all PDF file.
Let me suggest what I am doing wrong.
Thanks,
Bhavin

**Comment by JoanZapata** [comment]
Sorry, this is related to the [underlying rendering library](https://code.google.com/p/vudroid/).
