### ISSUE TITLE
Load files from Internal Storage

### ISSUE THREAD

**Issue by carstenbaumhoegger** [JoanZapata/android-pdfview#101]
Is it possible to load files from the internal storage with this lib?
It seems like its only possible to load files from assets.
I download the pdfs from the web into a folder on the internal storage, how can I show these files?

**Comment by tunjos** [comment]
The PDFView class has a ```.fromFile``` method. 
Simply pass in your FileUri. If you look at the source of **[PDFView.java](https://github.com/JoanZapata/android-pdfview/blob/master/android-pdfview/src/main/java/com/joanzapata/pdfview/PDFView.java#L967)**,
the ```.fromAsset``` actually calls this method.
```
pdfView.fromFile(FileUri)
                    .defaultPage(1)
                    .swipeVertical(true)
                    .showMinimap(false)
                    .enableSwipe(true)
                    .load();
```

**Comment by carstenbaumhoegger** [comment]
perfect, thank you very much! :)
