### ISSUE TITLE
In Fragment established as android:layout_width=“match_parent” not work

### ISSUE THREAD

**Issue by aldakur** [JoanZapata/android-pdfview#102]
I have one problem witch PDFViewer.
I use PDFViewer inside ViewPager, but I do not get the result I want. 
I have two screenshot. On is a actual picture and the other one with with the result I want. My PDF file has 3 page.

This is my code iin java:
http://pastebin.com/U9ACR4yN 

And this ins my code in xml:
http://pastebin.com/9pSBjetA

This is real screeanshot:
http://i.stack.imgur.com/PVde2.png

And this is the result I want:
http://i.stack.imgur.com/OK9Ug.png

Tnahk You!

**Comment by JoanZapata** [comment]
I don't think you'll get PDFView to work that way. 
Your best shot would probably be to find some lib to convert your pdf into images and load them in ImageViews in your ViewPager.

**Comment by aldakur** [comment]
Ok.Thank You!
