### ISSUE TITLE
How to add bangla font ?

### ISSUE THREAD

**Issue by amirul10022** [JoanZapata/android-pdfview#108]
I try to add bangla font following way. First put font SolaimanLipi.ttf to assets folder of the android-pdfview-sample. I follow the instruction of typeface helper , the link is given below 
https://github.com/norbsoft/android-typeface-helper
I write the following code in the PDFViewActivity class as below.
import static com.joanzapata.TypefaceHelper.typeface;

 @Override      // normal use of typeface
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        TypefaceCollection typeface = new TypefaceCollection.Builder().set(Typeface.NORMAL,Typeface.createFromAsset(getAssets(),"SolaimanLipi.ttf")).create();
        TypefaceHelper.init(typeface);
    }

I also write the code to use static use in display() method
  typeface(pdfView);// static use of typeface using static import TypefaceHelper

But could not properly work.
Can you help me please!

**Comment by JoanZapata** [comment]
Typeface can not be used to render the PDF. You can't change the typeface of your document using PDFView.
