### ISSUE TITLE
Error when importing to Android Studio

### ISSUE THREAD

**Issue by FireFly3000** [JoanZapata/android-pdfview#109]
Hello
I get this error when adding the maven dependency in Android Studio 1.2.1.1: 

**Warning:Packaging for dependency com.joanzapata.pdfview:android-pdfview:1.0.3 is 'apklib' and is not supported. Only 'aar' libraries are supported.**

I added it through: File -> Project structure -> Dependencies -> Add -> Library dependency. Here I found the following library and added it: com.joanzapata.pdfview:android-pdfview_1.0.3

Is there any solution for this?

**Comment by FireFly3000** [comment]
I have found a solution, howerver, I don't know if that is how it is supposed to be. I did the same as described in the problem. After this I added @arr to the dependency in gradle.

**Comment by JoanZapata** [comment]
It's how it's supposed to be, as you can see in the main page.
