### ISSUE TITLE
What is minimap?

### ISSUE THREAD

**Issue by zavernutiy** [JoanZapata/android-pdfview#157]
Hello, I wanted to ask what is minimap showing? Because I don't see any difference when the flag is either true of false. I need to make a view, where the thumbnails of all pages in pdf will be shown, and you can jump to any of them on click. I thought minimap will show me all that pages, but for now I don't understand what is it doing at all.

**Comment by zavernutiy** [comment]
I've found the answer myself. If anyone is interested, minimap shows the part of the page which is now zoomed in.

**Comment by maliknabil** [comment]
HI,
Have you done with the thumbnail of pages task using this library or any other? 
I also want to do the same but stuck in this task from last week. Can you plz help me?

**Comment by zavernutiy** [comment]
Hi, unfortunately I didn't succeed in creating thumbnails with this lib. So I have to move on the paid one http://www.radaeepdf.com/

**Comment by maliknabil** [comment]
Thanks @zavernutiy
