### ISSUE TITLE
[Question] Convert a PDF page to a bitmap and render as needed

### ISSUE THREAD

**Issue by vedant1811** [JoanZapata/android-pdfview#174]
Hello,  I am trying to create a bitmap from the PDF page. I went through the `DecodeServiceBase` and tried to the following:

            DecodeService decodeService = new DecodeServiceBase(new PdfContext());
            decodeService.setContentResolver(context.getContentResolver());
            decodeService.open(Uri.fromFile(pdf));
            int pageCount = decodeService.getPageCount();
            for (int i = 1; i <= pageCount; i++) {
                decodeService.decodePage(new Object(),
                        i,
                        bitmap -> { // callback
                            try {
                                File outputFile = new File(outputDir, System.currentTimeMillis() + FileUtils.DOT_JPEG);
                                FileOutputStream outputStream = new FileOutputStream(outputFile);
                                bitmap.compress(Bitmap.CompressFormat.JPEG, 100, outputStream);
                                outputStream.close();
                                subscriber.onNext(outputFile);
                            } catch (IOException e) {
                                LogWrapper.fatalError(e);
                            }
                        },
                        1, // zoom level
                        new RectF(0, 0, 1920, 1080)); // probably an incorrect input
            }

But I the callback method is never called.

What am I missing, what is the correct way to extract the entire bitmap rather than use the `PDFView` to display?

**Comment by VivianaGarces** [comment]
Have you found a solution for this?

**Comment by vedant1811** [comment]
@VivianaGarces yes I did. This is how: http://stackoverflow.com/a/34784937/1396264
