### ISSUE TITLE
 PDF file is corrupted

### ISSUE THREAD

**Issue by balasaheb143** [JoanZapata/android-pdfview#23]
java.lang.RuntimeException: An error occured while executing doInBackground()
Caused by: java.lang.RuntimeException: PDF file is corrupted
at:
static PdfDocument openDocument(String fname, String pwd)
    {
        return new PdfDocument(open(FITZMEMORY, fname, pwd));
    }
in PdfDocument  class

**Comment by milon87** [comment]
Hi, getting the same problem when to open pdf using vdfview.FromFile(); but opening from asset folder working fine.
Can you please tell us or any suggestion how to resolve this issue.
