### ISSUE TITLE
Support 64Bit abi

### ISSUE THREAD

**Issue by Mojtaba-Shafaei** [JoanZapata/android-pdfview#242]
There is no **x86_64** in the lib folder, so the library does not support all 64 bit devices.
Google did not allow to deploy a new release until solve that.

**Comment by Bhavesh-Moradiya** [comment]
Is there any way to generate 64 bit support library..... or any alternate for this one ?

**Comment by Mojtaba-Shafaei** [comment]
I have not see that this library is deprecated :(. 
I used https://github.com/barteksc/AndroidPdfViewer as instead but it increased about 10MB apk file.

I'm closing this issue
