### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by houssine20** [JoanZapata/android-pdfview#33]
hi guys , can you help me becouse i'm newbie 
i improt android-pdfview on eclipse but ,i had Mistakes :
![swwwans titre](https://cloud.githubusercontent.com/assets/7302125/2710691/8ffdca2a-c4c4-11e3-9f5b-6a78461e7584.png)
thnx...

**Comment by vikasrktm** [comment]
just add compile thing in your gradle build
and copy contents of libs in your projects lib folder
