### ISSUE TITLE
Is it possible to set a LongClickListener

### ISSUE THREAD

**Issue by gaztesk** [JoanZapata/android-pdfview#35]
Is it possible to set a LongClickListener to a PDFView like this?

PDFView.setOnLongClickListener

or maybe the PDFView has its own method to do it?

Thanks in advance

**Comment by wushipan123** [comment]
I rewrite some  code to achieve this function

1.com.joanzapata.pdfview.PDFView
public void setCustomOnTouchListener(OnTouchListener customOnTouchListener){
    	dragPinchManager.setCustomOnTouchListener(customOnTouchListener);;
    }

2.com.joanzapata.pdfview.DragPinchManager
public void setCustomOnTouchListener(OnTouchListener customOnTouchListener){
    	dragPinchListener.setCustomOnTouchListener(customOnTouchListener);;
    }

3.com.joanzapata.pdfview.util.DragPinchListener
private OnTouchListener customOnTouchListener;
public void setCustomOnTouchListener(OnTouchListener customOnTouchListener){
    	this.customOnTouchListener=customOnTouchListener;
    }

@Override
    public boolean onTouch(View v, MotionEvent event) {
    	if(customOnTouchListener!=null && customOnTouchListener.onTouch(v, event)==true){
    		return true;
    	}
        	……
		……
    }

4.myActivity
private long clickTime = 0;
private long TimeInterval = 500;
float x1, x2, y1, y2;


pdfView.setCustomOnTouchListener(new OnTouchListener() {

			@Override
			public boolean onTouch(View v, MotionEvent event) {
				// TODO Auto-generated method stub
				switch (event.getAction()) {
				case MotionEvent.ACTION_POINTER_2_DOWN:
					mHandler.removeMessages(0);
					break;
				case MotionEvent.ACTION_DOWN:
					x1 = event.getX();
					y1 = event.getY();
					// System.out.println("ACTION_DOWN");
					clickTime = System.currentTimeMillis();
					mHandler.sendEmptyMessageDelayed(0, TimeInterval);
					break;
				case MotionEvent.ACTION_MOVE:
					// System.out.println("ACTION_MOVE");
					x2 = event.getX();
					y2 = event.getY();
					if (Math.abs(x1 - x2) > 20) {
						mHandler.removeMessages(0);
					}
					break;
				case MotionEvent.ACTION_UP:
					if ((System.currentTimeMillis() - clickTime) < TimeInterval) {
						mHandler.removeMessages(0);
					}

					// System.out.println("ACTION_UP");
					break;
				default:
					break;
				}
				return false;
			}
		});
	}
	Handler mHandler=new Handler(){

		@Override
		public void handleMessage(Message msg) {
			// TODO Auto-generated method stub
			super.handleMessage(msg);
			switch (msg.what) {
			case 0:
				OnLongClick();
				break;

			default:
				break;
			}
		}
		
	};
	private void OnLongClick(){
		//onlongclick callback
	}
