### ISSUE TITLE
Set orientation of the pdf

### ISSUE THREAD

**Issue by lopezzbelgium** [JoanZapata/android-pdfview#36]
![horizontal](https://cloud.githubusercontent.com/assets/1770598/3053102/c40b3cd4-e1a3-11e3-97fb-26e744b2ced0.jpg)
Right now, some pdfs are displayed in portrait mode while the device is in landscape (see image). I guess this is due to the calculations (width height of a page). But this is pretty strange behaviour I think so it would be nice if there was an extra setting that forces all pages to be displayed horizontal or vertical.

So that the pages are readable in the same orientation the device is in..

**Comment by vangorra** [comment]
Any status on being able to manually specify the orientation?

**Comment by leonacky** [comment]
I have a same problem. Please let me know how to fix it
