### ISSUE TITLE
Scroll up and down to navigation between the pages in the PDF

### ISSUE THREAD

**Issue by mano-mykingdom** [JoanZapata/android-pdfview#44]
As of now, the user has to swipe in horizontal direction to navigate between the pages. Is it possible to have the same in vertical direction?

**Comment by sush4042** [comment]
Can we scroll up and down pdf pagewith latest version of pdfview jar?

**Comment by sush4042** [comment]
Looking for  horizontal direction scroll for pdf, is there any changes with new versions of jar?

**Comment by livenplay** [comment]
@sush4042 you can use <a href="https://github.com/johan12345/android-pdfview">this</a> fork and import it to your project as an android library project and it's supports the vertical swipe.

**Comment by mano-mykingdom** [comment]
@JoanZapata If you could merge the vertical scroll feature here, would be great. Thanks.

**Comment by JoanZapata** [comment]
Done, will release when I got some time. Thanks @johan12345

**Comment by mano-mykingdom** [comment]
Great, thanks.

**Comment by sush4042** [comment]
Great, Thanks Joan, Wainting for new relese.

**Comment by sush4042** [comment]
Hello Johan, please can you reply, when It should be publish? it will take how many days? Please reply.

**Comment by JoanZapata** [comment]
Will be done by tomorrow.

**Comment by sush4042** [comment]
Really Its Greate, Thanks a lot Joan for urgent reply. Thank you so much!!!!

**Comment by JoanZapata** [comment]
The pull request is actually very old so I don't think that counts as an urgent reply. :)
Anyway the release is done, it should be available in a few hours from maven central.
Thanks again @johan12345 and sorry for the delay!

**Comment by sush4042** [comment]
Hi Joan, where I will get the new release jar for scroll Up-down for move to new page? please provide the link.
Thank you.

**Comment by JoanZapata** [comment]
The same place you got the last one.
You can find everyting on [maven central](http://search.maven.org/#artifactdetails%7Ccom.joanzapata.pdfview%7Candroid-pdfview%7C1.0.3%7Capklib).

**Comment by undale** [comment]
I have tried new jar uploaded on 13 th may but the vertical scroll is not working

**Comment by undale** [comment]
Page will only change when i scroll horizontally

**Comment by JoanZapata** [comment]
Horizontal scrolling is still the default.
Use `.swipeVertical(true)` to enable the vertical scrolling on `1.0.3`.

**Comment by undale** [comment]
I have used pdfView.setSwipeVertical(true), but still animation while page loading is horizontal and swipe is working for diagonal direction.

**Comment by JoanZapata** [comment]
@johan12345 ?

**Comment by undale** [comment]
I have used .SetSwipeVertical(true),but still the the animation while page changing is horizontal and swipe is working for diagonal direction.

**Comment by johan12345** [comment]
Did you use `.swipeVertical` on the `Configurator` or `.setSwipeVertical` on the PDFView? It could be that the latter does not work when the view has already loaded the PDF file. I used the following code (edited from the demo app) and it works:
```
pdfView.fromAsset(assetFileName)
                .defaultPage(pageNumber)
                .onPageChange(this)
                .swipeVertical(true)
                .load();
```

**Comment by JoanZapata** [comment]
> It could be that the latter does not work when the view has already loaded the PDF file.

(which is perfectly fine)

**Comment by sush4042** [comment]
Hi Johan, thanks Its great and working fine. 

You have handle the own exceptions on rendering pdf and try to read the corrupted file on SDcard? (Inside RenderingAsyncTask file) unable to catch the generic exception in application.

**Comment by undale** [comment]
Hi Johan

     An Exception occurs when we try to read a corrupted pdf.Please can u try to solve these exception it occurs in "RenderingAsyncTask" file and we are  unable to catch these exception it would be a great help if u solve these problem

Thank your

**Comment by JoanZapata** [comment]
@undale #29

**Comment by naveedahmad99** [comment]
@johan12345 your vertical Scrolling solution also worked for me. Thanks

**Comment by razinahmd** [comment]
THANK YOU!!!

**Comment by nishanthan89** [comment]
Thanks Joan
