### ISSUE TITLE
PDF rendering issues

### ISSUE THREAD

**Issue by mpociot** [JoanZapata/android-pdfview#53]
Hi Joan,

first of all - thank you for this great library.

I have an issue with the PDF rendering when I zoom in. 

Please take a look at the attached screenshot.

Do you have an idea why this problem occurs?

![screenshot_2014-07-03-10-35-56](https://cloud.githubusercontent.com/assets/804684/3467278/c093d032-028e-11e4-8841-8896bac321b4.jpg)

**Comment by floouuu** [comment]
Hi! 
Where can I change the grid size?
Regards,
Florian

**Comment by gibbz-one** [comment]
Hello,
we have the same rendering issues. It stays like this for ever. It happens on a Samsung Galaxy Note 10.1 2014 edition.  
Where on the code we can try to alter the grid size to fix this issue?
Thank You!

![screenshot_2015-06-17-16-25-57](https://cloud.githubusercontent.com/assets/4599804/8209874/aa708c3e-150f-11e5-8b85-de54e1d64180.png)

**Comment by mpociot** [comment]
You can change the default grid size in Constants.java

Take a look here:

https://github.com/JoanZapata/android-pdfview/blob/d14913a0fe4ffdff2c7b53d65be88757db641a91/android-pdfview/src/main/java/com/joanzapata/pdfview/util/Constants.java#L45

**Comment by floouuu** [comment]
Hi! 
Changing the grid size didn't work for me. Maybe the grid size change solution is just a happy side effect.
However, what worked for me was calling `pdfView.loadPages();` in the onLoad function.
Here the code for jumping to a specified page (currentPage);
```
        pdfView.fromFile(f)
                .defaultPage(1)
                .onLoad(new OnLoadCompleteListener() {
                    @Override
                    public void loadComplete(int l) {
                        pdfView.zoomTo(ZOOM_FACTOR);
                        pdfView.loadPages();
                        // ...
                    }
                }).load();
```
I also use the loadPages() function when I'm jumping to the next page.

I hope this helps, cheers, Florian

**Comment by gibbz-one** [comment]
Thank You floouuu and mpociot for your responses. Sadly none of these worked for me. 
I forgot to mention that the rendering issue is bigger when the page is zoomed. When the page is not zoomed we have not rendering issue.
Trying to change some constant values, we saw that the rendering issue is mitigated when the PART_SIZE is around 768.
I hope for a more stable solution!
Thanks again!

**Comment by rashidmoidu** [comment]
Could any one please tell me how to make that change to the GRID_SIZE ???
coz i am a noob ,i have added pdfview 1.0.4 as dependancy in android studio....

**Comment by matheusjardimb** [comment]
The problem is still happening in Nexus 5 (Android5.1.1). 
Shouldn't this GRID_SIZE be increased in the repo by default? To solve this problem I need to clone it and change the constant, is it?

I don't think this issue should have been closed.

**Comment by AhmadullahSaikat** [comment]
GRID_SIZE = 10
