### ISSUE TITLE
Slow rendering

### ISSUE THREAD

**Issue by IlyaBlokh** [JoanZapata/android-pdfview#69]
Hello!
I'm trying to use an amazing android-pdfview library in my app. However pdf rendering is veeery slow. Viewer shows a blank white screen about 2-4 sec and then starts to render:
![screenshot_2014-10-03-18-29-17](https://cloud.githubusercontent.com/assets/1507182/4505712/616f62fc-4af9-11e4-8d26-f7a03f30abd6.png)
(device: Nexus 7 first generation).
Pdf has only 1 page but it remains unreadable during several seconds while viewer is slowly making the document readable by square zones.
Yes, finally pdf is readable, but it takes more than 10-15 seconds - totally user-unfriendly.
Is it common problem? How could I accelerate rendering?

**Comment by vikasrktm** [comment]
@IlyaBlokh ,hey bro ,did you find a solution of this slow rendering problem .
i also need to find a way to show pdf files in my android app.

**Comment by JoanZapata** [comment]
> This framework turns the PDF into a bitmap, so what you're seeing, I believe, is the low resolution image that is pre-populated quickly into the view before the higher resolution image tiles can load. If you can edit your PDFs, there may be some work there you can do to make them less resource intensive, but otherwise, I think you're at the mercy of this library for rendering.

Exactly. And this lib is at the mercy of [VuDroid](https://code.google.com/p/vudroid/) which is at the mercy of [MuPDF](http://mupdf.com/). Unfortunately there's not much I can do.
