### ISSUE TITLE
Loading Pdf from sdcard fromFile() CorruptedPdf

### ISSUE THREAD

**Issue by vnh1991** [JoanZapata/android-pdfview#76]
I am trying to open the pdf from the device's sd card but i always end up with pdf corrupted error
(same error even after taking the pdf's from the assets folder and kept it on my sdcard and gave its path)
## Code Snippet

File file = new File("/storage/emulated/legacy/sample.pdf");
Integer pageNumber = 1;
pdfView.fromFile(file).defaultPage(pageNumber)
            .onPageChange(this).load();
## Error Log

11-16 21:36:29.709: E/AndroidRuntime(27355): FATAL EXCEPTION: AsyncTask #1
11-16 21:36:29.709: E/AndroidRuntime(27355): Process: com.example.ptest, PID: 27355
11-16 21:36:29.709: E/AndroidRuntime(27355): java.lang.RuntimeException: An error occured while executing doInBackground()
11-16 21:36:29.709: E/AndroidRuntime(27355):    at com.joanzapata.pdfview.util.AsyncTask$3.done(AsyncTask.java:328)
11-16 21:36:29.709: E/AndroidRuntime(27355):    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
11-16 21:36:29.709: E/AndroidRuntime(27355):    at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
11-16 21:36:29.709: E/AndroidRuntime(27355):    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
11-16 21:36:29.709: E/AndroidRuntime(27355):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-16 21:36:29.709: E/AndroidRuntime(27355):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-16 21:36:29.709: E/AndroidRuntime(27355):    at java.lang.Thread.run(Thread.java:841)
11-16 21:36:29.709: E/AndroidRuntime(27355): Caused by: java.lang.RuntimeException: PDF file is corrupted
11-16 21:36:29.709: E/AndroidRuntime(27355):    at org.vudroid.pdfdroid.codec.PdfDocument.open(Native Method)
11-16 21:36:29.709: E/AndroidRuntime(27355):    at org.vudroid.pdfdroid.codec.PdfDocument.openDocument(PdfDocument.java:28)
11-16 21:36:29.709: E/AndroidRuntime(27355):    at org.vudroid.pdfdroid.codec.PdfContext.openDocument(PdfContext.java:18)
11-16 21:36:29.709: E/AndroidRuntime(27355):    at org.vudroid.core.DecodeServiceBase.open(DecodeServiceBase.java:59)
11-16 21:36:29.709: E/AndroidRuntime(27355):    at com.joanzapata.pdfview.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:49)
11-16 21:36:29.709: E/AndroidRuntime(27355):    at com.joanzapata.pdfview.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:1)
11-16 21:36:29.709: E/AndroidRuntime(27355):    at com.joanzapata.pdfview.util.AsyncTask$2.call(AsyncTask.java:317)
11-16 21:36:29.709: E/AndroidRuntime(27355):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-16 21:36:29.709: E/AndroidRuntime(27355):    ... 3 more

**Comment by fingerart** [comment]
Ha ha, I was careless, did not check the authority, thank you !

**Comment by ragh2009** [comment]
I have same issue and I had added permission also after that getting same issue.
Please share your comment on this.

**Comment by ghost** [comment]
Mine shows no errors but doesn't display the pdf either.
