### ISSUE TITLE
PDF renders off screen

### ISSUE THREAD

**Issue by thefwz** [JoanZapata/android-pdfview#77]
Awesome library & thanks for the effort.

I have a pdf that refuses to render properly. In my app I'm saving this url to internal storage (https://www.alislam.org/alfazl/rabwah/A20140424.pdf) then using .fromFile(...) to load it.

I don't get any errors but the result is as below:
![screenshot 10-40am nov 27 2014](https://cloud.githubusercontent.com/assets/434225/5210528/540a9844-7622-11e4-8f1f-43deb1ed74cd.png)

Other random pdf I've tried work just fine. Any ideas?

Thanks!

**Comment by JoanZapata** [comment]
It has to do with the [underlying rendering library](https://code.google.com/p/vudroid/).

**Comment by koraxis** [comment]
Hi Everyone, 

I have the same issue with many pdfs too. Is there any update on this one?
