### ISSUE TITLE
Interactive pdf file

### ISSUE THREAD

**Issue by nurwin** [JoanZapata/android-pdfview#78]
Hi there, Firstly I wanted to say that the library is great and seems easy to implement. But I want to know, can I use it in horizontal view? and can I load pdf with interactive content like video or audio inside the pdf?

Thanks,

**Comment by JoanZapata** [comment]
Hi, 
The default mode is horizontal, starting from version `1.0.3` you can also swipe pages vertically.
Interactive content will not be supported.
