### ISSUE TITLE
Blank pdf shows without any data

### ISSUE THREAD

**Issue by shahidrasul** [JoanZapata/android-pdfview#81]
When I tried to view the specific pdf. Pdf data does not display, only the blank white screen shows without any error. I am using Android 4.0 and test it on Nexus 7, Nexus 4 and Samsung S5.

Below is the Pdf screenshot
![pdf](https://cloud.githubusercontent.com/assets/6940696/5627360/d8687d94-95b8-11e4-9737-60f848faa569.jpg)

Below is the Pdf activity screenshot
![screenshot_2015-01-06-15-30-09](https://cloud.githubusercontent.com/assets/6940696/5627398/3e06cad4-95b9-11e4-914c-259052a26887.png)

**Comment by JoanZapata** [comment]
This is related to the underlying rendering library, [VuDroid](https://code.google.com/p/vudroid/).
