### ISSUE TITLE
Possibility to clear PDF cache

### ISSUE THREAD

**Issue by RoelRoel** [JoanZapata/android-pdfview#85]
Scenario: 
- I have created a PDF and showed in the PDFView
- The PDF gets deleted
- A new PDF is opened with the same name
- The PDFview shows the old PDF that is allready deleted?!?

**Comment by pavle93** [comment]
Have you try to call, after deleting the pdf?
```
pdfView1.invalidate();
```

**Comment by RoelRoel** [comment]
Thank you for the quick response. Sorry it was my mistake. The content I placed on the PDF was cached. It had nothing to do with your library.
