### ISSUE TITLE
Signed document cant open 

### ISSUE THREAD

**Issue by jenuprasad** [JoanZapata/android-pdfview#88]
Hi Joan,
I've tried to open a signed pdf document but i cant see the signature in it
can you help me

**Comment by UnateD** [comment]
I have a similar problem. Adobe Reader via I add handwritten comments, but when you open it through the library, I do not see these comments

**Comment by JoanZapata** [comment]
Those are not supported by the underlying library (vudroid / mupdf) so pdfview won't handle it, sorry.
