### ISSUE TITLE
Problem in openning pdf with background pictures.

### ISSUE THREAD

**Issue by emplab** [JoanZapata/android-pdfview#92]
I'm using this library. Every thin is ok but I have problem with pdf that have background picture.
For example I have a pdf that have an image on the background with 50% transparency.
If I open it with my app that powered with this library, the picture show on the text and text is hide under the picture.
What is the problem? I have a wrong in my code? or .... ?
please help me.

**Comment by JoanZapata** [comment]
It has to do with the underlying library (vudroid / mupdf), and therefore cannot be fixed from pdfview. Feel free to open an issue on their tracker https://code.google.com/p/vudroid/.
