### ISSUE TITLE
Handwritten comments are not visible when you open the file

### ISSUE THREAD

**Issue by UnateD** [JoanZapata/android-pdfview#94]
Good afternoon. In my application opens a file pdf, which were created in the mobile version of adobe reader. Comments that are painted on the pdf file in pencil will not be displayed if the files to open the library. However, displaying the inserted signature. Is it possible to somehow make the handwriting is displayed when using the library?
For example:
In my app with Pdfview lib
![2075138786c9f6b837233d52c4f48081](https://cloud.githubusercontent.com/assets/2272110/7005014/4a57919c-dc7c-11e4-8e9d-6125ba18f492.png)

In adobe reader mobile
![587da69b421d802b88f06d86c4265bd4](https://cloud.githubusercontent.com/assets/2272110/7005021/550a12a4-dc7c-11e4-9620-a58a7ca5ca2f.png)

**Comment by JoanZapata** [comment]
All the rendering is made using the [vudroid](https://code.google.com/p/vudroid/) library. If they don't provide it, neither does `pdfview`, sorry.
